#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Brent Yoder"
email = "499565+InAbsentia@users.noreply.github.com"

[[--scope]]
--when.commands = ["diff", "show"]
[--scope.ui]
pager = "delta"
diff-formatter = ":git"

[ui]
default-command = "status"
